name: build_and_test
on: [push]
jobs:
  build_and_test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: python3 -m pip install numpy setuptools invoke python-dotenv
      - run: python3 -m pip install --upgrade build
      - run: invoke build --python=python3

