name: build_and_test
on: [push]
jobs:
  build_and_test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: python3 -m pip install numpy setuptools
      - run: python3 -m pip install --upgrade build
      - run: python3 -m pip install .
      - run: python3 main.py
      - run: python3 -m unittest chesspy.tests  

