name: build_and_test
on: [push]
jobs:
  build_and_test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: brew install pdm 
      - run: pdm install
      - run: pdm build
      - run: python3 -m unittest chesspy.tests  

